name: Schedule script
on:
  schedule:
    - cron: '10 8 * * *' # every day at 8:10 AM UTC ( 2:40 AM IST)
jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
    steps:
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install requests json time twitter
      - name: Run script
        run: python3 ./../../script.py
