name: Schedule script
on:
  schedule:
    - cron: '0 18 * * *' # every day at 6 PM
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Run script
        run: python3 ./../../script.py
