name: Schedule script
on:
  schedule:
    - cron: '30 23 * * *' # every day at 11:30 AM UTC ( 6:00 PM IST)
jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
    steps:
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install requests json time twitter
      - name: Run script
        run: python3 ./../../script.py
