name: Schedule script
on:
  schedule:
    - cron: '0 18 * * *' # every day at 11:30 AM UTC ( 6:00 PM IST)
  push:
    branches:
      - main
jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
      CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
      CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
      TWITTER_TOKEN: ${{ secrets.TWITTER_TOKEN }}
      TWITTER_TOKEN_SECRET: ${{ secrets.TWITTER_TOKEN_SECRET }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip' # caching pip dependencies
      - name: Install dependencies
          run: pip install -r requirements.txt
      - name: Run script
          run: python3 script.py
