name: Schedule script
on:
  schedule:
    - cron: '30 23 * * *' # every day at 11:30 AM UTC ( 6:00 PM IST)
  push:
    branches:
      - main
jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
    steps:
      - name: Install dependencies
        run: python3 -m pip install --upgrade pip
      - name: Install requests package
        run: pip install requests
      - name: Install twitter package
        run: pip install twitter
      - name: Install replicate package
        run: pip install replicate
      - name: Run script
        run: python3 ./../../script.py
